# Generated by Django 2.0.4 on 2018-05-01 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=6000)),
                ('date_commentaire', models.DateField()),
                ('have_image', models.BooleanField(default=False)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Image')),
                ('liked_by', models.ManyToManyField(to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Acceptée'), (2, 'Refusée'), (3, 'Bloquée')])),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.Profil')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.BooleanField()),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('statut_groupe', models.CharField(choices=[('Publique', 'Publique'), ('Prive', 'Privé')], max_length=255)),
                ('have_image', models.BooleanField(default=False)),
                ('adherents', models.ManyToManyField(related_name='adherent', to='main_app.Profil')),
                ('admins', models.ManyToManyField(related_name='admin', to='main_app.Profil')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='main_app.Profil')),
                ('mederators', models.ManyToManyField(related_name='moderateur', to='main_app.Profil')),
                ('photo_couverture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_cover', to='main_app.Image')),
                ('photo_profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_photo', to='main_app.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('message', models.CharField(max_length=1000)),
                ('statut', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(default=False)),
                ('profil_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Responseconversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=6000)),
                ('message_date', models.DateTimeField()),
                ('is_image', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Conversation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Image')),
                ('user_responsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statut', models.DateTimeField()),
                ('contenu_statut', models.CharField(max_length=6000)),
                ('is_group_statut', models.BooleanField(default=False)),
                ('is_profil_statut', models.BooleanField(default=False)),
                ('liked_by', models.ManyToManyField(related_name='like', to='main_app.Profil')),
                ('mur_groupe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe')),
                ('mur_profil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_mur', to='main_app.Profil')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suive', to='main_app.Profil')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveur', to='main_app.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='demandegroupe',
            name='groupe_recepteur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='statut',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='main_app.Profil'),
        ),
        migrations.AlterUniqueTogether(
            name='demandeami',
            unique_together={('emetteur', 'recepteur')},
        ),
    ]
