# Generated by Django 2.0.4 on 2018-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='adherents',
            field=models.ManyToManyField(null=True, related_name='adherent', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='mederators',
            field=models.ManyToManyField(null=True, related_name='moderateur', to='main_app.Profil'),
        ),
    ]
