# Generated by Django 2.0.4 on 2018-05-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180507_0038'),
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField()),
                ('statut_groupe', models.CharField(choices=[('publique', 'publique'), ('prive', 'privé')], max_length=255)),
                ('adherents', models.ManyToManyField(related_name='adherent', to='main_app.Profil')),
                ('admins', models.ManyToManyField(related_name='admin', to='main_app.Profil')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='main_app.Profil')),
                ('mederators', models.ManyToManyField(related_name='moderateur', to='main_app.Profil')),
                ('photo_couverture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_cover', to='main_app.Image')),
                ('photo_profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_photo', to='main_app.Image')),
            ],
        ),
    ]
