# Generated by Django 2.0.4 on 2018-05-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180507_0038'),
        ('SocialMedia', '0002_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.BooleanField()),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
                ('groupe_recepteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe')),
            ],
        ),
    ]
