# Generated by Django 2.0.4 on 2018-05-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_auto_20180502_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='have_image',
        ),
    ]
