# Generated by Django 2.0.4 on 2018-05-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_remove_groupe_have_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeami',
            options={'ordering': ['id']},
        ),
    ]
