# Generated by Django 2.0.4 on 2018-05-04 17:34

import SocialMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0005_album_reseausocialfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseausocialfile',
            name='fichier',
            field=models.FileField(upload_to=SocialMedia.models.generate_path),
        ),
    ]
