# Generated by Django 2.0.4 on 2018-05-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180507_0038'),
        ('SocialMedia', '0006_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Acceptée'), (2, 'Refusée'), (3, 'Bloquée')])),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.Profil')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main_app.Profil')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='demandeami',
            unique_together={('emetteur', 'recepteur')},
        ),
    ]
