# Generated by Django 2.0.4 on 2018-05-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180507_0038'),
        ('SocialMedia', '0007_auto_20180507_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suive', to='main_app.Profil')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveur', to='main_app.Profil')),
            ],
        ),
    ]
