# Generated by Django 2.0.4 on 2018-05-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0007_auto_20180504_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseausocialfile',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Album'),
        ),
    ]
