# Generated by Django 2.0.4 on 2018-05-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_reseausocialfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseausocialfile',
            name='name',
        ),
    ]
