# Generated by Django 2.0.4 on 2018-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0010_remove_reseausocialfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='adherents',
            field=models.ManyToManyField(related_name='adherent', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='mederators',
            field=models.ManyToManyField(related_name='moderateur', to='main_app.Profil'),
        ),
    ]
