# Generated by Django 2.0.4 on 2018-05-06 23:53

import SocialMedia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180507_0038'),
        ('SocialMedia', '0011_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseauSocialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=SocialMedia.models.generate_path)),
                ('date_telechargement', models.DateTimeField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Album')),
                ('comment', models.ManyToManyField(to='SocialMedia.Commentaire')),
                ('likes', models.ManyToManyField(to='SocialMedia.Like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
    ]
