# Generated by Django 2.0.4 on 2018-05-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180507_0038'),
        ('SocialMedia', '0013_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=300)),
                ('diplome_requis', models.CharField(max_length=300)),
                ('type_contrat', models.CharField(max_length=300)),
                ('description_poste', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('presentation_entreprise', models.TextField()),
                ('type_emploi', models.CharField(blank=True, choices=[('plein', 'Plein temps'), ('partiel', 'Temps partiel')], default='', max_length=300, null=True)),
                ('nom_poste', models.CharField(blank=True, max_length=300, null=True)),
                ('en_cours', models.BooleanField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise')),
                ('poste', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste_recherche', to='SocialMedia.Poste')),
                ('profil_postulants', models.ManyToManyField(related_name='profil_postulants', to='main_app.Profil')),
                ('profil_publicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_publicateur', to='main_app.Profil')),
            ],
        ),
    ]
