# Generated by Django 2.0.4 on 2018-05-06 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0013_auto_20180506_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
