# Generated by Django 2.0.4 on 2018-05-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0014_auto_20180506_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='user',
        ),
        migrations.DeleteModel(
            name='OffreEmploi',
        ),
    ]
