# Generated by Django 2.0.4 on 2018-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0015_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
    ]
