# Generated by Django 2.0.4 on 2018-05-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180504_1726'),
        ('SocialMedia', '0015_auto_20180506_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionBenevole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisme', models.CharField(max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('cause', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actuel', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=300)),
                ('domaine', models.CharField(blank=True, max_length=300, null=True)),
                ('resultat_obtenu', models.CharField(blank=True, max_length=300, null=True)),
                ('activite_et_associations', models.TextField(blank=True, null=True)),
                ('annee_debut', models.DateField()),
                ('annee_fin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], max_length=300)),
                ('profils', models.ManyToManyField(related_name='profils', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=300)),
                ('diplome_requis', models.CharField(max_length=300)),
                ('type_contrat', models.CharField(max_length=300)),
                ('description_poste', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('presentation_entreprise', models.TextField()),
                ('en_cours', models.BooleanField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise')),
                ('profil_postulants', models.ManyToManyField(related_name='profil_postulants', to='main_app.Profil')),
                ('profil_publicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_publicateur', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='organisme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Organisme'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Poste'),
        ),
    ]
