# Generated by Django 2.0.4 on 2018-05-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180504_1726'),
        ('SocialMedia', '0016_auto_20180506_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='formation',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
    ]
