# Generated by Django 2.0.4 on 2018-05-06 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0017_auto_20180506_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
    ]
