# Generated by Django 2.0.4 on 2018-05-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0019_actionbenevole_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionbenevole',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
    ]
