# Generated by Django 2.0.4 on 2018-05-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0020_auto_20180506_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='nom_ecole',
            new_name='nom_formation',
        ),
    ]
